export const curatedHindiPhrases: Record<string, string> = {
  'About': 'परिचय',
  'Doctors': 'डॉक्टर',
  'Departments': 'विभाग',
  'Services': 'सेवाएं',
  'Trauma Center': 'ट्रॉमा सेंटर',
  'Facilities': 'सुविधाएं',
  'Gallery': 'गैलरी',
  'Contact': 'संपर्क',
  'Book Appointment': 'अपॉइंटमेंट बुक करें',
  'Emergency Call': 'आपातकालीन कॉल',
  'WhatsApp Consult': 'व्हाट्सएप पर संपर्क करें',
  'WhatsApp Consultation': 'व्हाट्सएप पर संपर्क करें',
  'Apply Now': 'अभी आवेदन करें',
  'Download Prospectus': 'प्रॉस्पेक्टस डाउनलोड करें',
  'Download Interactive Prospectus': 'इंटरैक्टिव प्रॉस्पेक्टस डाउनलोड करें',
  'Visit College Website': 'कॉलेज वेबसाइट देखें',
  'Visit Nursing College': 'नर्सिंग कॉलेज देखें',
  'Apply For Admission': 'प्रवेश के लिए आवेदन करें',
  'Admissions Application': 'प्रवेश आवेदन',
  'Submit Admissions Form': 'प्रवेश फॉर्म जमा करें',
  'Application Submitted!': 'आवेदन जमा हो गया!',
  'Admissions Open 2026': 'प्रवेश 2026 खुले हैं',
  'Admissions Open': 'प्रवेश खुले हैं',
  'ANM & GNM Seats Open': 'ANM और GNM सीटें खुली हैं',
  'Brochure': 'ब्रोशर',
  'Hospital General Portal': 'हॉस्पिटल मुख्य पोर्टल',
  'Official Campus Address': 'आधिकारिक कैंपस पता',
  'Learn • Train • Serve': 'सीखें • प्रशिक्षण लें • सेवा करें',
  'Enter Hospital Portal': 'हॉस्पिटल पोर्टल खोलें',
  'Visit Mata Bhagyamani Hospital': 'माता भाग्यमानी अस्पताल देखें',
  'Active Clinical Campus Hub': 'सक्रिय क्लिनिकल कैंपस हब',
  '100 Beds Active': '100 सक्रिय बेड',
  'Consult Doctors': 'डॉक्टर से परामर्श',
  'Admissions 2026': 'प्रवेश 2026',
  'Admission Helplines:': 'प्रवेश हेल्पलाइन:',
  'Courses': 'पाठ्यक्रम',
  'Admissions': 'प्रवेश',
  'Hostel Facility': 'हॉस्टल सुविधा',
  'Scholarship Support': 'छात्रवृत्ति सहायता',
  'Hospital-Based Clinical Training': 'हॉस्पिटल आधारित क्लिनिकल प्रशिक्षण',
  'Modern Science & Practical Labs': 'आधुनिक विज्ञान और प्रैक्टिकल लैब',
  'Modern Library': 'आधुनिक पुस्तकालय',
  'Smart Classrooms': 'स्मार्ट क्लासरूम',
  'Practical Nursing Training': 'प्रैक्टिकल नर्सिंग प्रशिक्षण',
  'Viva Examination Session': 'वाइवा परीक्षा सत्र',
  'Clinical Learning Experience': 'क्लिनिकल लर्निंग अनुभव',
  'Student Name': 'छात्र का नाम',
  'Mobile Number': 'मोबाइल नंबर',
  'Target Course': 'लक्षित पाठ्यक्रम',
  'Email Address': 'ईमेल पता',
  'Applicant Name *': 'आवेदक का नाम *',
  'Mobile Phone Number *': 'मोबाइल फोन नंबर *',
  'Desired Course': 'इच्छित पाठ्यक्रम',
  'Qualification': 'योग्यता',
  'City / Town Name': 'शहर / कस्बे का नाम',
  'ANM Diploma': 'ANM डिप्लोमा',
  'Paramedical': 'पैरामेडिकल',
  'GNM Diploma (Upcoming)': 'GNM डिप्लोमा (जल्द)',
  'B.Sc Nursing (Upcoming)': 'B.Sc नर्सिंग (जल्द)',
  '12th Pass': '12वीं पास',
  '10th Pass': '10वीं पास',
  'Graduate': 'स्नातक',
  'Official Prospectus Access Catalog': 'आधिकारिक प्रॉस्पेक्टस एक्सेस कैटलॉग',
  'Prospectus Access Link Dispatched!': 'प्रॉस्पेक्टस एक्सेस लिंक भेज दिया गया!',
  'Ramdhari Singh Admissions Office': 'रामधारी सिंह प्रवेश कार्यालय',
  'Course Curriculum': 'पाठ्यक्रम संरचना',
  'Primary Curriculum Modules (By Year)': 'मुख्य पाठ्यक्रम मॉड्यूल',
  'Key Career Placements Under this Certificate': 'इस प्रमाणपत्र के अंतर्गत प्रमुख करियर अवसर',
  'attached with 100-bed hospital': '100 बेड अस्पताल से संबद्ध',
  'All Photos': 'सभी फोटो',
  'Trauma & Critical Units': 'ट्रॉमा और क्रिटिकल यूनिट',
  'Patient Support': 'रोगी सहायता',
  'Technical & Building': 'तकनीकी और भवन',
  'Close Gallery': 'गैलरी बंद करें',
  'Close Profile': 'प्रोफाइल बंद करें',
  'Close Info Desk': 'सूचना डेस्क बंद करें',
  'Corporate Profile': 'कॉर्पोरेट प्रोफाइल',
  'Mata Bhagyamani Devi Hospital': 'माता भाग्यमानी देवी अस्पताल',
  'Hospital & Trauma Center': 'अस्पताल और ट्रॉमा सेंटर',
  'Patient-First Care': 'रोगी-प्रथम देखभाल',
  'Modern Diagnostic Tech': 'आधुनिक जांच तकनीक',
  'Government Empanelled': 'सरकारी पैनल में शामिल',
  'Nursing College Partner': 'नर्सिंग कॉलेज सहयोगी',
  'Our Medical Services': 'हमारी चिकित्सा सेवाएं',
  'Ayushman PM-JAY Scheme': 'आयुष्मान PM-JAY योजना',
  'Consultations & Contact': 'परामर्श और संपर्क',
  'Advanced Trauma Hub': 'उन्नत ट्रॉमा हब',
  'OPD Clinical Specialities': 'OPD क्लिनिकल विशेषज्ञताएं',
  'Diagnostics & Ultrasound': 'डायग्नोस्टिक्स और अल्ट्रासाउंड',
  'Maternity & Neonatal ICU': 'मातृत्व और नवजात ICU',
  'Cashless Eligibility Checker': 'कैशलेस पात्रता जांच',
  'Required Documents list': 'आवश्यक दस्तावेज सूची',
  'Arogya Mitra Desk timing': 'आरोग्य मित्र डेस्क समय',
  'Book Primary Appointment': 'मुख्य अपॉइंटमेंट बुक करें',
  'Emergency Hotline: 24h': 'आपातकालीन हेल्पलाइन: 24 घंटे',
  'Our Sakari Mod Location': 'हमारा सकरी मोड़ स्थान',
  'Medical Board Members': 'मेडिकल बोर्ड सदस्य',
  'General Line: +91 94708 26108': 'सामान्य लाइन: +91 94708 26108',
  'All Rights Reserved.': 'सर्वाधिकार सुरक्षित।',
};
